language: php

php:
  - "5.5"
  - "5.4"
  - "5.3"

install:
  - sudo apt-get install python python-pip
  - sudo pip install --requirement=requirements.txt
  - composer install --prefer-dist --dev

script: phpunit

notifications:
  email: false
  on_success: never
  on_failure: always