<?php

namespace Fobia;

class TableSheets2 extends TableSheets
{

    public static function getProg($prog)
    {
        return parent::getProg($prog);
    }

    public static function isWin()
    {
        return parent::isWin();
    }

}

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-03-31 at 12:42:36.
 */
class TableSheetsTest extends \PHPUnit_Framework_TestCase
{

    public function testIsWin()
    {
        $this->assertEquals(false, TableSheets2::isWin());
    }

    public function testGetProgn()
    {
        $p = sprintf("@^/usr/bin/python .*?%s$@", TableSheets::CMD_TO_CSV);
        $r = (bool) preg_match($p, TableSheets2::getProg(TableSheets::CMD_TO_CSV));
        $this->assertEquals(true, $r);
    }

}
