<?php

namespace Fobia;

class TableSheets2 extends TableSheets
{

    public static function getProg($prog)
    {
        return parent::getProg($prog);
    }

    public static function isWin()
    {
        return parent::isWin();
    }

}

define("DATA_DIR", dirname(__FILE__) . '/../../data');
define("FIXED_CSV", dirname(__FILE__) . '/../../data/fixed.csv');
define("TMP_CSV", '/tmp/1.csv');

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-03-31 at 12:42:36.
 */
class TableSheetsTest extends \PHPUnit_Framework_TestCase
{

    public function testIsWin()
    {
        $this->assertEquals(false, TableSheets2::isWin());
    }

    public function testGetProgn()
    {
        $p = sprintf("@^/usr/bin/python .*?%s$@", TableSheets::CMD_TO_CSV);
        $r = (bool) preg_match($p, TableSheets2::getProg(TableSheets::CMD_TO_CSV));
        $this->assertEquals(true, $r);
    }


    public function testToCsvCP1251()
    {
        $f = DATA_DIR . '/cp1251.csv';
        $this->assertEquals(true, TableSheets::toCSV($f, TMP_CSV));
        $this->assertEquals(md5_file(TMP_CSV), md5_file(FIXED_CSV));
    }

    // public function testToCsvExcel2003()
    // {
    //     $f = DATA_DIR . '/excel2003.xls';
    //     $this->assertEquals(true, TableSheets::toCSV($f, TMP_CSV));
    //     $this->assertEquals(md5_file(TMP_CSV), md5_file(FIXED_CSV));
    // }
}
